services:
  producer:
    build: ./producer
    env_file: ./producer/.env.producer
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      initialize-queue:
        condition: service_completed_successfully
    volumes: 
      - producer-libs:/usr/local/lib/python3.8/site-packages
    container_name: producer
  consumer:
    build: ./consumer
    environment: 
      - PYTHONUNBUFFERED=1
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASS
      - RABBITMQ_PORT=5672
      - TASK_QUEUE=task_queue
    volumes: 
      - /usr/local/lib/python3.8/site-packages
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      producer:
        condition: service_started
  initialize-queue:
    build: ./job
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: ./job/.env.job 
    volumes: 
      - job-libs:/usr/local/lib/python3/site-packages
      - /usr/local/lib/python3.8/site-packages
  api:
    build: ./api
    depends_on:
      mongodb:
        condition: service_healthy
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - FLASK_SERVER_ADDR=api:5000
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started
    container_name: web-svc
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - /var/log/rabbitmq/
      - /var/usr/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
volumes:
  rabbitmq-data:
    size: 0.5Gi
  mongodb-data:
    size: 0.5Gi
  producer-libs:
    size: 0.5Gi
  job-libs:
    size: 0.5Gi