services:
  producer:
    build: ./producer
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASS=rabbitmq
      - RABBITMQ_PORT=5672
      - TASK_QUEUE=task_queue
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - producer:/app
    container_name: producer
  consumer:
    build: ./consumer
    env_file: consumer/.env
    depends_on:
      - rabbitmq
      - mongodb
  api:
    build: ./api
    depends_on:
      - mongodb
    expose:
      - 5000
  nginx:
    image: public.ecr.aws/nginx/nginx:latest
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - FLASK_SERVER_ADDR=api:5000
    ports:
      - 80:80
    depends_on:
      - api
    container_name: web-svc
  rabbitmq:
    image: quay.io/bitnami/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - /var/log/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
volumes:
  rabbitmq-data:
  mongodb-data:
